#!/usr/bin/bash
# Run "copr -a" to build project.tar.gz.

TIME=$(date +%H%M%S)
SCRIPT=build-$TIME
ID=${SCRIPT}
HDIR=/tmp
CDIR=/tmp

if [ "$1" == "win" ]; then
	echo '
  mkdir ~/.cache
  mkdir atlush
  cd atlush
  tar xf /tmp/project.tar.gz
  copr -t mingw
' >$HDIR/${SCRIPT}

	podman run -d -it --name=$ID dev/f33-mingw:1.2 /bin/bash || exit
	podman cp project.tar.gz $ID:$CDIR
	podman cp $HDIR/${SCRIPT} $ID:$CDIR/${SCRIPT}
	podman exec -it -u build $ID /bin/bash $CDIR/${SCRIPT}
	podman cp $ID:/home/build/atlush/atlush.exe /tmp/atlush.exe-$TIME

	# Build zip archive.
	FN=`readlink -f arc/mingw-qt_app.tar.gz`
	tar xf $FN -C /tmp
	cp /tmp/atlush.exe-$TIME /tmp/qt_app/atlush.exe
	cd /tmp; mv qt_app atlush; zip -r atlush.zip atlush
else
	echo '
  mkdir atlush
  cd atlush
  tar xf /tmp/project.tar.gz
  copr
' >$HDIR/${SCRIPT}

	podman run -d -it --name=$ID dev/centos8:1.0 /bin/bash || exit
	podman cp project.tar.gz $ID:$CDIR
	podman cp $HDIR/${SCRIPT} $ID:$CDIR/${SCRIPT}
	podman exec -it $ID /bin/bash $CDIR/${SCRIPT}
	podman cp $ID:/home/build/atlush/atlush /tmp/atlush-$TIME
fi

echo "$SCRIPT done!"
podman stop $ID
